apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/ingress

patches:
  - path: backend/replicas.yaml
  - path: frontend/replicas.yaml


images:
  - name: loanhub-backend
    newName: 612069931326.dkr.ecr.ap-south-1.amazonaws.com/loanhub-backend
    newTag: latest
  - name: loanhub-frontend
    newName: 612069931326.dkr.ecr.ap-south-1.amazonaws.com/loanhub-frontend
    newTag: latest
